
name: Terraform Deploy
on:
  push:
    branches: [main]
env:
  AZURE_WEBAPP_NAME: your-webapp-name
  AZURE_WEBAPP_PACKAGE_PATH: './web'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Azure Login
        run: |
          echo "Logging in with service principal..."
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          echo "Setting Azure subscription..."
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          echo "Listing available subscriptions..."
          az account list --output table
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    